APPUSER: student
APPHOME: /home/{{APPUSER}}
TOMCAT_STDOUT: "{{TOMCAT_VERSION.stdout}}"
TOCAT_MAJOR_VERSION: "{{ TOMCAT_STDOUT.split('.')[0] }}"
TOMCAT_URL: "https://archive.apache.org/dist/tomcat/tomcat-{{TOCAT_MAJOR_VERSION}}/v{{TOMCAT_VERSION.stdout}}/bin/apache-tomcat-{{TOMCAT_VERSION.stdout}}.tar.gz" 