- name: Install HTTPD server
  package: 
    name: httpd
    state: present

- name: copy proxy config file
  template: 
     src: proxy.conf
     dest: /etc/httpd/conf.d/proxy.conf  

- name: Download index html page from web
  get_url:
      url: "{{INDEX_URL}}"
      dest: /var/www/html/index.html

- name: Start and enable httpd service
  service:
    name: httpd
    state: restarted
    enabled: yes