- name: Add application User 
  user:
    name: "{{APPUSER}}"

- name: Print the tomcat url
  debug:
    msg: "{{TOMCAT_URL}}"

- name: Downlaod Tomcat 
  unarchive:
    src: "{{TOMCAT_URL}}"
    dest: "{{APPHOME}}"
    remote_src: yes
  become_user: "{{APPUSER}}"


