- name: Add app user
  user:
    name: "{{APPUSER}}"

- name: Print the tomcat url
  debug:
    msg: "{{ TOMCAT_URL }}"

- name: Download Tomcat
  unarchive:
       src: "{{TOMCAT_URL}}"
       dest: "{{APPHOME}}"
       remote_src: yes
  become_user: "{{APPUSER}}"

