- name: Demo on when condition statement
  hosts: all
  tasks:
    - name: Execute shell command
      shell: ls -ld /etc1
      register: out
      ignore_errors: yes

    - name: Print SUCCESS Message
      debug: 
        msg: "Command was SUCCESS"
      when: out.rc == 0

    - name: Print Failure Message
      debug:
        msg: "Command was FAILURE"
      when: out.rc != 0