## Tags are used to run particular tasks

- name: Demo on Tags
  hosts: all
  tasks:
   
    - debug:
        msg: "web installation"
      tags: 
         - web
         - httpd
         - nginx
    - debug: 
        msg: "App installation"
      tags: 
         - app
         - tomcat             

## We can run this command as ansible-playbook Playbooks/10-tags.yml -t web
