- name: Demo on loops concept
  hosts: all
  tasks:

   - name: Demo on loop
     debug: 
       msg: "Hello, {{ item }}"
     loop:
        - john
        - Teja
        - Pt


### to check the user

- name: Check the user
  hosts: all
  tasks:
    - shell: id
      register: out
    - debug:
        msg: "{{out.stdout}}"