- name: Demo on become user
  hosts: all
  #become: yes
  tasks: 
   - name: Get the Id
     shell: id
     register: out
     become: yes ## this command is used to become sudo user, You can also become sudo user at play level as shown above
   - debug:
       msg: "{{out.stdout}}"